# Generated by Django 5.2.17 on 2026-08-18 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pandascore_id', models.BigIntegerField(unique=True)),
                ('tournament_name', models.CharField(max_length=255)),
                ('videogame', models.CharField(max_length=100)),
                ('team1_name', models.CharField(max_length=100)),
                ('team1_logo_url', models.URLField(blank=True)),
                ('team2_name', models.CharField(max_length=100)),
                ('team2_logo_url', models.URLField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('running', 'Running'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('winner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bets_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_team', models.CharField(max_length=100)),
                ('stake', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost')], default='active', max_length=20)),
                ('payout', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='matches.match')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'match'), name='one_active_bet_per_match')],
            },
        ),
    ]
